### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by leoheck** [vyvledav/ADMeshGUI#5]
Is it possible to add a screenshot in the readme?

**Comment by hroncok** [comment]
There is https://github.com/admesh/ADMeshGUI/blob/master/Distribution/screenshot1.png and https://github.com/admesh/ADMeshGUI/blob/master/Distribution/screenshot2.png -- would you be able to send a PR with the README changes?

**Comment by leoheck** [comment]
of course, this is nice.
--
Leandro Heck

**Comment by hroncok** [comment]
Thank You! Fixed in https://github.com/admesh/ADMeshGUI/pull/6
